#!/bin/bash
URL=$1
FILE=$2
TIMESTAMP_BEGIN=`gdate +%s%N`
OUTPUT=`curl $URL`
TIMESTAMP_END=`gdate +%s%N`
DURATION=$((TIMESTAMP_END - TIMESTAMP_BEGIN))
echo `echo "$TIMESTAMP_BEGIN,$TIMESTAMP_END,$DURATION,$OUTPUT" >> $FILE`