'use strict';

exports.mem_load = function(req, res) {
  var c = 0;
  var arr = new Array();
  for(var i = 0; i < 99;i++){
    var string = 'ABCDABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZ';
    for(var z = 0; z < 50;z++){
        string += 'ABCDEFGHIJKLMNOPQRSTUVXABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZ';
        for(var y = 0; y < 50;y++){
          string += 'ABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZABCDEFGHIJKLMNOPQRSTUVXZ';
          arr.push(string);
          c += 1;
      }
    }
  }
  res.json(c); 
};

exports.cpu_load = function(req, res) {
  var c = 0;
  var arr = new Array();
  for(var i = 0; i < 99;i++){
    for(var z = 0; z < 99;z++){
        for(var y = 0; y < 99;y++){
          arr.push(i+z+y);
          c += 1;
      }
    }
  }
  res.json(c); 
};

exports.io_load = function(req, res) {
  var c = 0;
  var arr = new Array();
  for(var i = 0; i < 9;i++){
    for(var z = 0; z < 9;z++){
        for(var y = 0; y < 99;y++){
          var fs = require('fs');
          fs.writeFileSync('/tmp/fs.tmp'+i+z+y, i+z+y);
          c += 1;
      }
    }
  }
  res.json(c); 
};
